- hosts: web
  become: true
  gather_facts: false
  tasks:
  - name: install apache
    yum: name=httpd state=latest
    notify:
    - start apache
    ignore_errors: true
    tags:
    - install
  - name: copy index.html
    template: src=app/index.html dest=/var/www/html/
    tags:
    - copy
  - name: dynamic content
    debug:
      msg: "{{index}}"
    tags:
    - index
  handlers:
  - name: start apache
    service: name=httpd state=started
    tags:
    - start

